// Code generated by create-ga-config.js, DO NOT EDIT.
// You can use 'yarn tracking'.
const GA_EVENT_STRING = {
  "DT_Header_Button_Timers": {
    "category": "Header",
    "action": "click",
    "label": "DT_Header_Button_Timers"
  },
  "DT_Header_Button_Add_Timer": {
    "category": "Header",
    "action": "click",
    "label": "DT_Header_Button_Add_Timer"
  },
  "DT_Header_Button_Menu": {
    "category": "Header",
    "action": "click",
    "label": "DT_Header_Button_Menu"
  },
  "DT_Timers_Item_To_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "DT_Timers_Item_To_Timer"
  },
  "DT_Timers_Button_Edit_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "DT_Timers_Button_Edit_Timer"
  },
  "DT_Timers_Button_Delete_Timer": {
    "category": "Timers",
    "action": "click",
    "label": "DT_Timers_Button_Delete_Timer"
  },
  "DT_TimersEditor_Button_Submit": {
    "category": "TimerEditor",
    "action": "click",
    "label": "DT_TimersEditor_Button_Submit"
  }
};
export default GA_EVENT_STRING;
